import fs from 'node:fs'
import path from 'node:path'
import { sendText, botInfo } from '#helper'

async function handler({ sock, m, jid }) {
    if (!m.q || !m.q.message) {
        return await sendText(sock, jid, "Lu harus nge-reply pesan nya!", m)
    }

    const targetMessage = m.q.message

    try {
        const json = JSON.stringify(targetMessage, (key, value) => {
            const forbiddenKeys = [
                'messageContextInfo', 
                'deviceListMetadata', 
                'deviceListMetadataVersion', 
                'invokerJid', 
                'toJSON', 
                'bitchannelContextInfo'
            ]
            if (forbiddenKeys.includes(key)) return undefined
            
            if (value && typeof value === 'object' && value.low !== undefined && value.high !== undefined) {
                return value.low 
            }
            
            if (value && value.type === 'Buffer' && Array.isArray(value.data)) {
                return `___B64___${Buffer.from(value.data).toString('base64')}___B64___`
            }

            return value
        }, 2)

        const payload = json.replace(/"___B64___(.+?)___B64___"/g, 'Buffer.from("$1", "base64")')

        const codeSnippet = `/* generated by Near\n * gunakan command .run untuk mengeksekusi file ini\n */\n\nawait sock.relayMessage(jid, ${payload}, {})\n`

        // PENENTUAN NAMA FILE DENGAN RANDOM STRING
        const randomStr = Math.random().toString(36).slice(2, 8)
        const fileName = `relayMessage-${randomStr}.js`

        const tempDir = './user/temp'
        const filePath = path.join(tempDir, fileName)

        if (!fs.existsSync(tempDir)) {
            fs.mkdirSync(tempDir, { recursive: true })
        }
        
        fs.writeFileSync(filePath, codeSnippet)

        await sock.sendMessage(jid, {
            document: fs.readFileSync(filePath),
            mimetype: 'application/javascript',
            fileName: fileName,
            caption: `ini relay message nya!`
        }, { quoted: m })

        setTimeout(() => { 
            if (fs.existsSync(filePath)) fs.unlinkSync(filePath) 
        }, 5000)

    } catch (err) {
        console.error('[Error CRM]:', err)
        await sendText(sock, jid, `Gagal memproses CRM:\n${err.message}`, m)
    }
}

handler.pluginName = 'Code Relay Message v4'
handler.description = 'Mengambil raw payload dari pesan dan mengubahnya jadi script relayMessage.'
handler.command = ['crm']
handler.category = ['utility', 'owner']

handler.meta = { 
    fileName: 'crm.js', 
    version: '4.0.5', 
    author: botInfo.an,
    note: 'Fixed filename to relayMessage-{random}.js'
}

export default handler